### ISSUE TITLE
ARM binaries

### ISSUE THREAD

**Issue by Alex-Programs** [stellitecoin/GUI-miner#11]
I just spent the last 2 hours failing at installing go... now it's complaining about no path when I just gave it a bloody path.

Anyway, it would take you very little time and make it a lot easier for people if you attached ARM binaries.

**Comment by donovansolms** [comment]
I'm not 100% sure if Electron works on ARM, I'll need to look into that.

**Comment by Alex-Programs** [comment]
OK thanks. Sorry about being mad earlier.

**Comment by donovansolms** [comment]
No problem, we want to make mining as simple and easy as possible. Knowing that people would like an ARM version is great.

**Comment by Alex-Programs** [comment]
Thanks for looking into it :)
